# Issue Labels Configuration
# This file defines all the labels used in the repository

# Priority Labels
- name: "priority: critical"
  color: "d73a4a"
  description: "Critical issues that need immediate attention"
- name: "priority: high"
  color: "d93f0b"
  description: "High priority issues"
- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority issues"
- name: "priority: low"
  color: "0e8a16"
  description: "Low priority issues"

# Type Labels
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "performance"
  color: "ff8c00"
  description: "Performance improvements or issues"
- name: "security"
  color: "ee0701"
  description: "Security vulnerabilities or improvements"

# Status Labels
- name: "needs-triage"
  color: "d4c5f9"
  description: "Issues that need initial review"
- name: "in-progress"
  color: "1d76db"
  description: "Work in progress"
- name: "blocked"
  color: "ff8c00"
  description: "Blocked by other issues or dependencies"
- name: "ready-for-review"
  color: "0e8a16"
  description: "Ready for code review"
- name: "needs-feedback"
  color: "fbca04"
  description: "Waiting for user feedback"

# Component Labels
- name: "component: web-app"
  color: "c2e0c6"
  description: "Web application related"
- name: "component: mobile-app"
  color: "c2e0c6"
  description: "Mobile app (Android TWA) related"
- name: "component: api"
  color: "c2e0c6"
  description: "API endpoints and backend"
- name: "component: rss-feeds"
  color: "c2e0c6"
  description: "RSS feed system"
- name: "component: music-tracks"
  color: "c2e0c6"
  description: "Music track management"
- name: "component: admin-panel"
  color: "c2e0c6"
  description: "Admin panel functionality"
- name: "component: caching"
  color: "c2e0c6"
  description: "Caching system"
- name: "component: images"
  color: "c2e0c6"
  description: "Image optimization and handling"

# Special Labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "invalid"
  color: "e4e669"
  description: "Something is wrong"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
