# Labeler Configuration
# Automatically labels issues and PRs based on file paths and content

# Web App Components
component: web-app:
  - 'src/app/**/*'
  - 'src/components/**/*'
  - 'src/lib/**/*'
  - 'src/styles/**/*'
  - 'public/**/*'

# Mobile App Components
component: mobile-app:
  - 'android/**/*'
  - 'src/app/manifest.json'
  - 'src/app/sw.js'
  - 'src/app/offline.html'

# API Components
component: api:
  - 'src/app/api/**/*'
  - 'src/lib/api/**/*'
  - 'src/types/api/**/*'

# RSS Feed Components
component: rss-feeds:
  - 'src/app/feeds/**/*'
  - 'src/lib/feeds/**/*'
  - 'src/types/feeds/**/*'

# Music Track Components
component: music-tracks:
  - 'src/app/tracks/**/*'
  - 'src/lib/tracks/**/*'
  - 'src/types/tracks/**/*'

# Admin Panel Components
component: admin-panel:
  - 'src/app/admin/**/*'
  - 'src/components/admin/**/*'
  - 'src/lib/admin/**/*'

# Caching Components
component: caching:
  - 'src/lib/cache/**/*'
  - 'src/app/api/cache/**/*'
  - 'next.config.js'
  - 'src/middleware.ts'

# Image Components
component: images:
  - 'src/lib/images/**/*'
  - 'src/app/api/images/**/*'
  - 'src/components/images/**/*'

# Documentation
documentation:
  - '**/*.md'
  - '**/*.txt'
  - 'docs/**/*'
  - '.github/**/*'

# Configuration Files
enhancement:
  - 'package.json'
  - 'package-lock.json'
  - 'yarn.lock'
  - 'tsconfig.json'
  - 'next.config.js'
  - 'tailwind.config.js'
  - '.env*'
  - '.eslintrc*'
  - '.prettierrc*'

# Dependencies
enhancement:
  - 'package.json'
  - 'package-lock.json'
  - 'yarn.lock'

# Security
security:
  - '.env*'
  - 'src/middleware.ts'
  - 'src/lib/auth/**/*'
  - 'src/app/api/auth/**/*'

# Performance
performance:
  - 'next.config.js'
  - 'src/middleware.ts'
  - 'src/lib/cache/**/*'
  - 'src/app/api/cache/**/*'
