[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "fuckit-app"

[services.variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[[services]]
name = "postgres"
plugin = "postgresql"

[services.variables]
POSTGRES_DB = "fuckit_music"
POSTGRES_USER = "fuckit_user"