blank_issues_enabled: false
contact_links:
  - name: 🚀 GitHub Discussions
    url: https://github.com/your-username/your-repo/discussions
    about: Please ask and answer questions here.
  - name: 📧 Email Support
    url: mailto:support@yourdomain.com
    about: Contact us directly for urgent issues.
  - name: 📖 Documentation
    url: https://yourdomain.com/docs
    about: Check our documentation first.
