name: Deploy to Server

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Create deployment directory
          DEPLOY_DIR="/var/www/re.podtards.com"
          BACKUP_DIR="/var/www/backup-$(date +%Y%m%d-%H%M%S)"
          
          # Backup current deployment
          if [ -d "$DEPLOY_DIR" ]; then
            sudo cp -r "$DEPLOY_DIR" "$BACKUP_DIR"
            echo "Backup created at $BACKUP_DIR"
          fi
          
          # Create deployment directory if it doesn't exist
          sudo mkdir -p "$DEPLOY_DIR"
          sudo chown $USER:$USER "$DEPLOY_DIR"
          
          # Stop the current application
          cd "$DEPLOY_DIR" && pm2 stop fuckit-app || true
          
          # Clean up old files
          sudo rm -rf "$DEPLOY_DIR"/*
          
          # Copy new files from GitHub
          sudo cp -r . "$DEPLOY_DIR/"
          sudo chown -R $USER:$USER "$DEPLOY_DIR"
          
          # Install dependencies
          cd "$DEPLOY_DIR"
          npm install --production
          
          # Start the application
          pm2 start ecosystem.config.js
          pm2 save
          
          echo "Deployment completed successfully!"
          
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi 