name: Issue Automation

on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issues
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

  issue-triage:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Auto-assign triage label
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels.map(l => l.name);
            
            // Add needs-triage label if not present
            if (!labels.includes('needs-triage')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['needs-triage']
              });
            }
            
            // Auto-assign based on component labels
            const componentLabels = labels.filter(l => l.startsWith('component:'));
            if (componentLabels.length > 0) {
              // You can customize this logic to auto-assign specific maintainers
              console.log(`Component labels found: ${componentLabels.join(', ')}`);
            }

  stale-issues:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Mark stale issues
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs. Thank you for your contributions.
          stale-issue-label: 'no-reminder'
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs. Thank you for your contributions.
          stale-pr-label: 'no-reminder'
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: 'pinned,security,priority: critical,priority: high'
          exempt-pr-labels: 'pinned,security,priority: critical,priority: high'
